### PR TITLE
feat: Provide /meta to the whole app

### PR DESCRIPTION
**Pull request by evancharlton**
Instead of fetching `/meta` several times throughout the app, fetch it once and expose it to all components through a context provider.

> NOTE: There is still a remaining `/meta` call through the area-edit
>       function. This will be removed when that API gets cleaned up.

### CODE REVIEW

**Comment by jossi87** [comment]
I'll merge it when the conflicts are resolved 🙂

**Comment by evancharlton** [comment]
Resolved!

**Comment by jossi87** [comment]
I guess I merged in the wrong order, sorry. New conflict

**Comment by evancharlton** [comment]
No problem - fixed!

**Pull request merged**
