### PR TITLE
feat: Improve filter/group/order options on problem list

### PR DESCRIPTION
**Pull request by evancharlton**
When looking at a sector (or area), the current experience is fairly lacking. A common scenario is when I'm already at a particular crag, and want to move to a different wall. Today, my options are to clumsily use the list of problems on the `/area/:areaId` page, or use the `/problems` page with some aggressive filtering.

This change aims to merge the two experiences. A subset of the filtering options (grades, types) are brought into the problem list, and the existing functionality is enhanced. The main enhancement is additional group-by options: area, sector, type, rock, and none. (Note that superfluous filter types are hidden when they aren't applicable).

### CODE REVIEW

**Comment by evancharlton** [comment]
I found some issues with this - stay tuned :)

**Comment by evancharlton** [comment]
@jossi87 - you're more familiar with the intricate user scenarios for this component, so it'd be great if you could take a pass over this in a local branch. I checked its usage in `/area/:areaId`, `/sector/:sectorId`, and on `/user/:userId`, and a quick smoke-test on both climbing and bouldering -- but I will readily accept if I missed a scenario :)

**Comment by evancharlton** [comment]
Thanks for the feedback, @jossi87! I also wasn't thrilled with the UI, so I'm glad you said something :-). I decided to put it behind a "Filter" item in the list - it seems to make sense to me: group the items by <dimension>, order them by <preference>, then optionally filter them down.

image

image

Please take a look and see how you feel about the new format.

> If you navigate to a user the "Order By" is empty (see below). It should be ordering by date as default.

Fixed!

> I find it strange that the sector page is ordering in descending order when you order routes/problems by number. It should be ascending.

Fixed!

**Comment by jossi87** [comment]
I tested it now, I like it! Great work!

**Pull request merged**
